version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.8
    - 7.13.9
  - dependency-name: immer
    versions:
    - 8.0.0
